/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_middlerim_queue_Writer */

#ifndef _Included_io_middlerim_queue_Writer
#define _Included_io_middlerim_queue_Writer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_middlerim_queue_Writer
 * Method:    init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_middlerim_queue_Writer_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_middlerim_queue_Writer
 * Method:    add
 * Signature: (JLjava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_io_middlerim_queue_Writer_add
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
