/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_middlerim_queue_Reader */

#ifndef _Included_io_middlerim_queue_Reader
#define _Included_io_middlerim_queue_Reader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_middlerim_queue_Reader
 * Method:    init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_middlerim_queue_Reader_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_middlerim_queue_Reader
 * Method:    read
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_middlerim_queue_Reader_read
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
