[package]
name = "writer_bench"
version = "0.1.0"
authors = [
  "sndyuk <sanada@sndyuk.com>",
]
edition = "2018"

[dependencies]
serde = "1"
serde_derive = "1"
clap = { git = "https://github.com/clap-rs/clap/", features = ["derive"] }
confy = "0"
shmem = { version = "0.1.0", path = "../shmem" }
