[package]
name = "shmem"
version = "0.1.0"
authors = [
  "sndyuk <sanada@sndyuk.com>",
]
edition = "2018"

[dependencies]
shared_memory = { git = "https://github.com/elast0ny/shared_memory-rs" }
serde = "1"
serde_derive = "1"
signal-hook = "0"
