[package]
name = "shmem"
version = "0.1.0"
authors = [
  "sndyuk <sanada@sndyuk.com>",
]
edition = "2018"

[dependencies]
raw_sync = { path = "../../raw_sync-rs" }
shared_memory = "0"
serde = "1"
serde_derive = "1"
signal-hook = "0"

[features]
default = []

replica_local = []
replica_tcp = []
