[package]
name = "reader_bench"
version = "0.1.0"
authors = [
  "sndyuk <sanada@sndyuk.com>",
]
edition = "2018"

[dependencies]
serde = "1"
serde_derive = "1"
clap = { version = "3.2.22", features = ["derive"] }
confy = "0"
shmem = { version = "0.1.0", path = "../shmem" }
