[package]
name = "reader_bench"
version = "0.1.0"
authors = [
  "sndyuk <sanada@sndyuk.com>",
]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
clap = { git = "https://github.com/clap-rs/clap/" }
confy = "0.4"
shmem = { version = "0.1.0", path = "../shmem" }
